# Generated by Django 4.0.3 on 2022-03-07 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
