# Generated by Django 4.0.4 on 2022-07-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_article_options_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_no', models.CharField(max_length=10)),
                ('coin_symbol', models.CharField(max_length=10)),
                ('coin_name', models.CharField(max_length=10)),
                ('coin_usd_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('coin_percent_change_24h', models.CharField(max_length=100)),
                ('coin_percent_change_7d', models.CharField(max_length=100)),
                ('coin_usd_market_cap', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('coin_usd_volume_24h', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('coin_circulating_supply', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('currencynumber', models.IntegerField(verbose_name='currencynumber')),
                ('unit', models.IntegerField(verbose_name='unit')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('currency', models.CharField(max_length=50, verbose_name='currency')),
                ('exchangedate', models.DateTimeField(verbose_name='exchangedate')),
                ('buy', models.FloatField(verbose_name='buy')),
                ('sell', models.FloatField(verbose_name='sell')),
                ('crossrate', models.FloatField(verbose_name='crossrate')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_id', models.IntegerField(verbose_name='curr_id')),
                ('curr_code', models.CharField(max_length=100, verbose_name='curr_code')),
                ('curr_name', models.CharField(max_length=100, verbose_name='curr_name')),
            ],
            options={
                'ordering': ['curr_id'],
            },
        ),
    ]
