# Generated by Django 4.0.4 on 2022-07-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_cryptocurrency_currency_currencylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='coin_name',
            field=models.CharField(max_length=100),
        ),
    ]
