# Generated by Django 4.0.4 on 2022-07-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_alter_cryptocurrency_coin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='coin_circulating_supply',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='coin_usd_market_cap',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='coin_usd_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='coin_usd_volume_24h',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
