# Generated by Django 4.0.4 on 2022-07-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_alter_cryptocurrency_coin_circulating_supply_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'ordering': ['-last_updated', '-coin_usd_price']},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-exchangedate', 'name']},
        ),
    ]
