# Generated by Django 4.0.3 on 2022-03-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_options_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('currencynumber', models.IntegerField(max_length=10, verbose_name='currencynumber')),
                ('unit', models.IntegerField(max_length=3, verbose_name='unit')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('currency', models.CharField(max_length=50, verbose_name='currency')),
                ('exchangedate', models.DateTimeField(verbose_name='exchangedate')),
                ('buy', models.FloatField(verbose_name='buy')),
                ('sell', models.FloatField(verbose_name='sell')),
                ('crossrate', models.FloatField(verbose_name='crossrate')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
